import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'MyMart',
      'product_details': 'Product Details',
      'my_orders': 'My Orders',
      'account_settings': 'Account Settings',
      'my_addresses': 'My Addresses',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'language': 'Language',
      'select_language': 'Select Language',
      'view_profile': 'View Profile',
      'my_coupons': 'My Coupons',
      'my_returns': 'My Returns',
      'my_reviews': 'My Reviews',
      'your_reviews': 'Your Reviews',
      'wishlist': 'Wishlist',
      'track_order': 'Track Order',
      'coupons': 'Coupons',
      'refund': 'Refund',
      'returns': 'Returns',
      'add_to_cart': 'Add to Cart',
      'buy_now': 'Buy Now',
      'quantity': 'Quantity',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'sold_by': 'Sold by',
      'related_products': 'Related Products',
      'total': 'Total',
      'search_products': 'Search products...',
      'categories': 'Categories',
      'home': 'Home',
      'cart': 'Cart',
      'profile': 'Profile',
      'login': 'Login',
      'register': 'Sign Up',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'submit': 'Submit',
      'help_center': 'Help Center',
      'about_us': 'About Us',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'loading': 'Loading...',
      'no_data': 'No data available',
      'no_products': 'No products to review yet',
      'no_returns': 'No return requests',
      'review_prompt': 'Review your delivered products here',
      'create_return': 'Create Return',
      'no_saved_cards': 'No saved cards',
      'add_card': 'Add a card for faster checkout',
      'english': 'English',
      'urdu': 'اردو',
      'arabic': 'العربية',
      'hindi': 'हिन्दी',
      'chinese': '中文',
      'stores': 'Stores',
      'all_stores': 'All Stores',
      'no_stores': 'No stores available yet',
      'no_stores_desc': 'Check back later for exciting stores!',
      'verified_store': 'Verified Store',
      'about_store': 'About Store',
      'phone': 'Phone',
      'email': 'Email',
      'no_products_yet': 'No products yet',
      'no_products_desc': 'This store has no products listed',
      'my_cart': 'My Cart',
      'clear': 'Clear',
      'clear_cart': 'Clear Cart',
      'clear_cart_confirm': 'Are you sure you want to remove all items from your cart?',
      'your_cart_empty': 'Your cart is empty',
      'start_shopping': 'Start shopping to add items',
      'start_shopping_btn': 'Start Shopping',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'discount': 'Discount',
      'checkout': 'Checkout',
      'proceed_checkout': 'Proceed to Checkout',
      'free': 'FREE',
      'unknown_store': 'Unknown Store',
      'orders_split': 'Orders will be split store-wise at checkout',
      'all_same_store': 'All items in cart are from this store',
      'no_description': 'No description available',
      'reviews': 'Reviews',
      'no_reviews': 'No reviews yet',
      'view_all_reviews': 'View all reviews',
      'password': 'Password',
      'phone_number': 'Phone Number',
      'forgot_password': 'Forgot password?',
      'no_account': 'Don\'t have an account?',
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'create_account': 'Create your account',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'confirm_password': 'Confirm Password',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'have_account': 'Already have an account?',
      'my_wishlist': 'My Wishlist',
      'wishlist_empty': 'Your wishlist is empty',
      'save_items': 'Save items you love!',
      'no_products_found': 'No products found',
      'check_back': 'Check back later for new products',
      'go_back': 'Go Back',
      'try_again': 'Try Again',
      'retry': 'Retry',
      'failed_to_load': 'Failed to load',
      'welcome': 'Welcome to MyMart',
      'shop_by_category': 'Shop by Category',
      'all_products': 'All Products',
      'login_required': 'Login Required',
      'login_to_wishlist': 'Please login to add items to your wishlist.',
      'login_to_cart': 'Please login first to add items to your cart.',
      'product': 'Product',
      'delivery_time': 'Delivery Time',
      'select_delivery_time': 'Select delivery time',
      'payment_method': 'Payment Method',
      'cash_on_delivery': 'Cash on Delivery',
      'pay_when_receive': 'Pay when you receive',
      'credit_debit_card': 'Credit/Debit Card',
      'pay_secure_stripe': 'Pay securely via Stripe',
      'order_summary': 'Order Summary',
      'delivery': 'Delivery',
      'free_delivery': 'Free Delivery!',
      'place_order': 'Place Order',
      'pay_with_card': 'Pay with Card',
      'processing': 'Processing...',
      'please_wait': 'Please wait a moment',
      'network_error': 'Network error. Please try again.',
      'order_failed': 'Failed to place order',
      'payment_failed': 'Payment failed',
      'payment_successful': 'Payment successful!',
      'location': 'Your Location',
      'detect_location': 'Detect my location',
      'deliver_here': 'Deliver to this location',
      'deliver_to': 'Deliver to',
      'email_address': 'Email Address',
      'enter_otp': 'Enter OTP',
      'otp_sent': 'We will send you an OTP on this number',
      'registration_successful': 'Registration Successful!',
      'check_email_otp': 'Please check your email for OTP verification.',
      'passwords_no_match': 'Passwords do not match',
      'registration_failed': 'Registration failed',
      'order_status': 'Order Status',
      'delivery_address': 'Delivery Address',
      'not_specified': 'Not specified',
      'cancel_order': 'Cancel Order',
      'write_review': 'Write a Review',
      'return_replace': 'Return / Replace',
      'cancel_confirm': 'Are you sure you want to cancel this order?',
      'order_cancelled': 'Order cancelled',
      'order_id_copied': 'Order ID copied',
      'max_stock': 'Maximum stock reached',
      'no_items': 'No items',
      'items': 'Items',
      'verified': 'Verified',
      'nearby': 'Nearby',
      'new': 'New',
      'items_saved_offline': 'items saved offline',
      'connect_for_details': 'Connect to the internet to see details',
    },
    'ur': {
      'app_name': 'مائی مارٹ',
      'product_details': 'مصنوعات کی تفصیلات',
      'my_orders': 'میرے آرڈرز',
      'account_settings': 'اکاؤنٹ کی ترتیبات',
      'my_addresses': 'میرے پتے',
      'payment_methods': 'ادائیگی کے طریقے',
      'notifications': 'اطلاعات',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'view_profile': 'پروفائل دیکھیں',
      'my_coupons': 'میرے کوپنز',
      'my_returns': 'میری واپسی',
      'my_reviews': 'میرے جائزے',
      'your_reviews': 'آپ کے جائزے',
      'wishlist': 'خواہش کی فہرست',
      'track_order': 'آرڈر ٹریک کریں',
      'coupons': 'کوپنز',
      'refund': 'ریفنڈ',
      'returns': 'واپسی',
      'add_to_cart': 'کارٹ میں شامل کریں',
      'buy_now': 'ابھی خریدیں',
      'quantity': 'مقدار',
      'in_stock': 'اسٹاک میں ہے',
      'out_of_stock': 'اسٹاک ختم',
      'sold_by': 'فروخت کنندہ',
      'related_products': 'متعلقہ مصنوعات',
      'total': 'کل',
      'search_products': 'مصنوعات تلاش کریں...',
      'categories': 'زمرے',
      'home': 'ہوم',
      'cart': 'کارٹ',
      'profile': 'پروفائل',
      'login': 'لاگ ان',
      'register': 'سائن اپ',
      'logout': 'لاگ آؤٹ',
      'cancel': 'منسوخ کریں',
      'save': 'محفوظ کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم کریں',
      'submit': 'جمع کریں',
      'help_center': 'مدد سینٹر',
      'about_us': 'ہمارے بارے میں',
      'privacy_policy': 'رازداری کی پالیسی',
      'terms_of_service': 'خدمات کی شرائط',
      'loading': 'لوڈ ہو رہا ہے...',
      'no_data': 'کوئی ڈیٹا دستیاب نہیں',
      'no_products': 'ابھی تک کوئی مصنوعات نہیں',
      'no_returns': 'واپسی کی کوئی درخواست نہیں',
      'review_prompt': 'اپنی ڈیلیور کردہ مصنوعات کا جائزہ لیں',
      'create_return': 'واپسی بنائیں',
      'no_saved_cards': 'کوئی محفوظ کارڈ نہیں',
      'add_card': 'تیز چیک آؤٹ کے لیے کارڈ شامل کریں',
      'english': 'انگریزی',
      'urdu': 'اردو',
      'arabic': 'عربی',
      'hindi': 'ہندی',
      'chinese': 'چینی',
    },
    'ar': {
      'app_name': 'ماي مارت',
      'product_details': 'تفاصيل المنتج',
      'my_orders': 'طلباتي',
      'account_settings': 'إعدادات الحساب',
      'my_addresses': 'عناويني',
      'payment_methods': 'طرق الدفع',
      'notifications': 'الإشعارات',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'view_profile': 'عرض الملف الشخصي',
      'my_coupons': 'كوبوناتي',
      'my_returns': 'مرتجعاتي',
      'my_reviews': 'تقييماتي',
      'your_reviews': 'تقييماتك',
      'wishlist': 'قائمة الرغبات',
      'track_order': 'تتبع الطلب',
      'coupons': 'الكوبونات',
      'refund': 'استرداد',
      'returns': 'مرتجعات',
      'add_to_cart': 'أضف إلى السلة',
      'buy_now': 'اشتر الآن',
      'quantity': 'الكمية',
      'in_stock': 'متوفر',
      'out_of_stock': 'غير متوفر',
      'sold_by': 'بائع',
      'related_products': 'منتجات ذات صلة',
      'total': 'المجموع',
      'search_products': 'ابحث عن منتجات...',
      'categories': 'التصنيفات',
      'home': 'الرئيسية',
      'cart': 'السلة',
      'profile': 'الملف الشخصي',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'submit': 'إرسال',
      'help_center': 'مركز المساعدة',
      'about_us': 'معلومات عنا',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_of_service': 'شروط الخدمة',
      'loading': 'جار التحميل...',
      'no_data': 'لا توجد بيانات',
      'no_products': 'لا توجد منتجات للمراجعة بعد',
      'no_returns': 'لا توجد طلبات إرجاع',
      'review_prompt': 'قيم منتجاتك التي تم توصيلها هنا',
      'create_return': 'إنشاء إرجاع',
      'no_saved_cards': 'لا توجد بطاقات محفوظة',
      'add_card': 'أضف بطاقة للدفع السريع',
      'english': 'الإنجليزية',
      'urdu': 'الأردية',
      'arabic': 'العربية',
      'hindi': 'الهندية',
      'chinese': 'الصينية',
    },
    'hi': {
      'app_name': 'माईमार्ट',
      'product_details': 'उत्पाद विवरण',
      'my_orders': 'मेरे ऑर्डर',
      'account_settings': 'खाता सेटिंग्स',
      'my_addresses': 'मेरे पते',
      'payment_methods': 'भुगतान के तरीके',
      'notifications': 'सूचनाएं',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'view_profile': 'प्रोफ़ाइल देखें',
      'my_coupons': 'मेरे कूपन',
      'my_returns': 'मेरी वापसी',
      'my_reviews': 'मेरी समीक्षाएं',
      'your_reviews': 'आपकी समीक्षाएं',
      'wishlist': 'इच्छा सूची',
      'track_order': 'ऑर्डर ट्रैक करें',
      'coupons': 'कूपन',
      'refund': 'रिफंड',
      'returns': 'वापसी',
      'add_to_cart': 'कार्ट में डालें',
      'buy_now': 'अभी खरीदें',
      'quantity': 'मात्रा',
      'in_stock': 'स्टॉक में है',
      'out_of_stock': 'स्टॉक खत्म',
      'sold_by': 'द्वारा बेचा गया',
      'related_products': 'संबंधित उत्पाद',
      'total': 'कुल',
      'search_products': 'उत्पाद खोजें...',
      'categories': 'श्रेणियां',
      'home': 'होम',
      'cart': 'कार्ट',
      'profile': 'प्रोफ़ाइल',
      'login': 'लॉगिन',
      'register': 'साइन अप',
      'logout': 'लॉग आउट',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'submit': 'जमा करें',
      'help_center': 'सहायता केंद्र',
      'about_us': 'हमारे बारे में',
      'privacy_policy': 'गोपनीयता नीति',
      'terms_of_service': 'सेवा की शर्तें',
      'loading': 'लोड हो रहा है...',
      'no_data': 'कोई डेटा उपलब्ध नहीं',
      'no_products': 'अभी तक कोई उत्पाद नहीं',
      'no_returns': 'कोई वापसी अनुरोध नहीं',
      'review_prompt': 'अपने डिलीवर किए गए उत्पादों की समीक्षा करें',
      'create_return': 'वापसी बनाएं',
      'no_saved_cards': 'कोई सहेजा गया कार्ड नहीं',
      'add_card': 'त्वरित चेकआउट के लिए कार्ड जोड़ें',
      'english': 'अंग्रेज़ी',
      'urdu': 'उर्दू',
      'arabic': 'अरबी',
      'hindi': 'हिंदी',
      'chinese': 'चीनी',
    },
    'zh': {
      'app_name': 'MyMart',
      'product_details': '产品详情',
      'my_orders': '我的订单',
      'account_settings': '账户设置',
      'my_addresses': '我的地址',
      'payment_methods': '支付方式',
      'notifications': '通知',
      'language': '语言',
      'select_language': '选择语言',
      'view_profile': '查看资料',
      'my_coupons': '我的优惠券',
      'my_returns': '我的退货',
      'my_reviews': '我的评价',
      'your_reviews': '您的评价',
      'wishlist': '收藏夹',
      'track_order': '追踪订单',
      'coupons': '优惠券',
      'refund': '退款',
      'returns': '退货',
      'add_to_cart': '加入购物车',
      'buy_now': '立即购买',
      'quantity': '数量',
      'in_stock': '有货',
      'out_of_stock': '缺货',
      'sold_by': '卖家',
      'related_products': '相关产品',
      'total': '总计',
      'search_products': '搜索产品...',
      'categories': '分类',
      'home': '首页',
      'cart': '购物车',
      'profile': '个人中心',
      'login': '登录',
      'register': '注册',
      'logout': '退出',
      'cancel': '取消',
      'save': '保存',
      'delete': '删除',
      'edit': '编辑',
      'submit': '提交',
      'help_center': '帮助中心',
      'about_us': '关于我们',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      'loading': '加载中...',
      'no_data': '暂无数据',
      'no_products': '暂无待评价产品',
      'no_returns': '暂无退货申请',
      'review_prompt': '在此评价您已收货的产品',
      'create_return': '创建退货',
      'no_saved_cards': '暂无保存的卡片',
      'add_card': '添加卡片以便快速结账',
      'english': '英语',
      'urdu': '乌尔都语',
      'arabic': '阿拉伯语',
      'hindi': '印地语',
      'chinese': '中文',
    },
  };

  static const Map<String, bool> rtlLanguages = {
    'ar': true,
    'ur': true,
  };

  bool get isRtl => rtlLanguages[locale.languageCode] == true;

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ?? _translations['en']?[key] ?? key;
  }

  static List<String> languageCodes = ['en', 'ur', 'ar', 'hi', 'zh'];
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.languageCodes.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) => Future.value(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
